config/routes.rb
Rails.application.routes.draw do
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  	root 'products#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
      if @product.save
        redirect_to products_path
      else
        render :new
      end
  end

  def edit
      @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
      if @product.update(product_params)
        redirect_to products_path
      else
        render :edit
      end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
    def product_params
      params.require(:product).permit(:name, :description, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<%= form_for @product do |f| %>
<div>
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>
<div>
  <%= f.label :description %>
  <%= f.text_area :description %>
</div>
<div>
  <%= f.label :price %>
  <%= f.number_field :price %>
</div>
<div>
  <%= f.submit %>
</div>
<% end %>

app/views/products/index.html.erb
<h1>Products list</h1>
<%= link_to "Create", new_product_path %>
<table>
  <thead>
    <th>Name</th>
    <th>Description</th>
    <th>Price</th>
  </thead>
  <% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.description %></td>
    <td><%= product.price %></td>
    <td>
      <%= link_to "Edit", edit_product_path(product) %>
      <%= link_to "Delete", product, method: :delete, data: { confirm: "Are you sure you want to delete this product?"} %>
    </td>
  </tr>
  <% end %>
</table>

app/views/products/new.html.erb
<%= form_for @product do |f| %>
<div>
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>
<div>
  <%= f.label :description %>
  <%= f.text_area :description %>
</div>
<div>
  <%= f.label :price %>
  <%= f.number_field :price %>
</div>
<div>
  <%= f.submit %>
</div>
<% end %>